json.id @session.id
json.service_name @session.service.biz_user.company_name
json.service_name @session.service.service_name
json.user_id @session.user.id
json.user_first_name @session.user.first_name
json.user_last_name @session.user.last_name
json.is_completed @session.is_completed
json.created_at @session.created_at
json.updated_at @session.updated_at
